import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AccountProvider } from "../contexts/AccountContext";
import HeaderComponent from "./components/Header/HeaderComponent";
import { ThemeProvider } from "@/contexts/ThemeContext";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Banking-app",
  description: "Generated by kiran gadhavi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300`}
      >
        <ThemeProvider>
          <AccountProvider>
            <HeaderComponent />
            <div className="pt-20 xs:pt-10">{children}</div>
          </AccountProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
